# _config.yml:
# Evidently ... DO NOT USE TABS in YAML!

# Development: https://wwwkwootcca.github.io/dev/
# Local:       http://localhost:4000/dev/ (K.I.S.S.)
# Production:  http://kwootc.ca/dev/ (www.kwootc.ca?)

#JEKYLL_ENV: production
# https://help.github.com/articles/basic-writing-and-formatting-syntax/

# # Where things are
# source:       .
destination:  ./_site
# destination:  ./_site/dev
# plugins_dir:  _plugins
# layouts_dir:  _layouts
# data_dir:     _data
# includes_dir: _includes
# collections:
#   posts:
#     output:   true
#
# # Handling Reading
# safe:         false
# include:      [".htaccess"]
include:        [".htaccess"]
# exclude:      ["node_modules", "vendor/bundle/", "vendor/cache/", "vendor/gems/", "vendor/ruby/"]
# keep_files:   [".git", ".svn"]
# encoding:     "utf-8"
# markdown_ext: "markdown,mkdown,mkdn,mkd,md"
#
# # Filtering Content
# show_drafts: null
# limit_posts: 0
# future:      false
# unpublished: false
show_drafts:  true
future:       true
unpublished: true
#
# # Plugins
# whitelist: []
# gems:      []
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-mentions
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-tidy  # Changing compress_html in chained config files not working.
                 # - it may seem jekyll-tidy is not working ('cause it's not
                 #   compressing. If files are indented nicely, it's working.
                 #   compress_html compresses, it doesn't tidy.
#
# # Conversion
#markdown:    { kramdown: { input: "GFM" } }
markdown:    kramdown
kramdown:    { input:   GFM }

# highlighter: rouge
# lsi:         false
lsi:           true
# excerpt_separator: "\n\n"
# incremental: false
incremental:   true
#
# # Serving
# detach:  false
# port:    4000
# host:    127.0.0.1
# baseurl: "" # does not include hostname
#          Keep set to non-blank - blank will always work, not so, reversed.
#          - keep reversed so issues are identified early.
# baseurl: ""
baseurl: "/dev" # when on github. K.I.S.S., be /dev everywhere.
# show_dir_listing: false
show_dir_listing: false
#
# # Outputting
# permalink:     date
permalink:     /Diary/:year/:month/:day/:title
# paginate_path: /page:num
# timezone:      null
timezone:      America/Toronto
#
# quiet:    false
# verbose:  false
# defaults: []
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
#     type:   "posts" - this would impact everything, e.g. css
    values:
      url:    "http://localhost:4000" # doesn't work.
      layout: "mydefault"
      author: "KWOOTC"

url: "http://localhost:4000"
#
# liquid:
#   error_mode: warn
liquid: {   error_mode: warn }
#    error_mode:    warn
#
# # Markdown Processors
# rdiscount:
#   extensions: []
#
# redcarpet:
#   extensions: []
#
# kramdown:
#   auto_ids:       true
#   footnote_nr:    1
#   entity_output:  as_char
#   toc_levels:     1..6
#   smart_quotes:   lsquo,rsquo,ldquo,rdquo
#   input:          GFM
#   hard_wrap:      false
#   footnote_nr:    1
#



imports: [./_sitevars.yml]

#profile: "true"

lang: en-ca

show_downloads: "false"           # Could be, e.g. (site.github.zip_url or site.github.tar_url)



theme:          minima            # Was jekyll-theme-slate

name:           KWOOTC            # Was "www.kwootc.ca Development Website"
title:          KWOOTC            # Was "www.kwootc.ca Development",
                                  # e.g. site.github.repository_name (jekyll-style-guide)
                                  #
                                  # description:
                                  # "www.kwootc.ca Development Repository",
                                  #  e.g. site.github.project_description ('')

description:    Kitchener-Waterloo Out Of The Cold

author:             wwwkwootcca
github_username:    wwwkwootcca
email:              wwwkwootcca@users.noreply.github.com
#twitter_username:   no_twitter_here@example.com

#                   https://help.github.com/articles/repository-metadata-on-github-pages/
#google_analytics:
google_analytics:  [UA-91236515-1]

#disqus: { shortname: no_disgust_here }

comments: true



repository: wwwkwootcca/dev

# GitHub Pages will overwrite - this keeps things working locally.
# - WHEN USING 'site.github.url'!
github: {   url: "http://localhost:4000/dev" }

compress_html:
  clippings:  all
# comments:   all
  comments:   ["<!-- ", " -->"]
  endings:    []
#  ignore:     { envs: ["development"] }
#    Squish the whitespace in all environments, now.
  blanklines: true
  startings:    []
# https://github.com/penibelst/jekyll-compress-html/releases/tag/v3.0.2
## Restrictions:
#* Whitespaces inside of the `textarea` element are squeezed. Please don’t use the layout on pages with non-empty `textarea`.
#* Inline JS can become broken where `//` comments used. Please remove the comments or change to `/**/` style.
#* Invalid markup can lead to unexpected results. Please make sure your markup is valid before.
# ---------
# Defaults:
# ---------
# clippings: [] (or 'all'), e.g. [div, p, ul, td, h1, h2] - clip surrounding whitespace
# comments: []  (or 'all'), e.g.  ["<!-- ", " -->"]       - remove comments
# - note whitespace in example. Conditional comments,
#   e.g. <!--[if expression]> HTML <![endif]--> or <![if expression]> HTML <![endif]>
#   would not be caught.
# endings: []   (or 'all'), e.g. [p, li, td]              - optional end tags, removed, e.g. </p>.
#  ignore:
#    envs: [development]
# blanklines: false                                       - remove lines consisting only of whitespace?
# profile: false                                          - append bytes saved stats at end?
# startings: []             e.g.  [html, head, body]      - optional start tags, removed, e.g. <html>.
# ---------

jekyll_tidy: { compress_html: true, exclude: [".htaccess"] }

#jekyll_tidy: { exclude: [ "/Diary", "/Diary/index.html" ], compress_html: true }
# - have never been able to get exclude: [ "whatever" ] to work.

# gem_loaded:   false
# exclude: sample.html
#  exclude: [/Test/index.html]
# Note: if you set the compress_html option to true and your templates have
#       inline CSS or javascript, it will not be minified.
#  compress_html: true

# Not that we're using redcarpet ...
# Something like:
#extensions:
#  redcarpet:
#    Markdown:
#      disable_indented_code_blocks:  true
#      lax_spacing:                   true
#      underline:                     true
#      ighlight:                    true

# SASS Source:
# .widget-social {
#     text-align: right;
#
#     a,
#     a:visited {
#         padding: 0 3px;
#         color: #222222;
#         color: rgba(34, 34, 34, 0.77);
#      }
#
#     a:hover {
#         color: #B00909;
#     }
#
# }
#
# :nested (default) - but sass puts all on one line, so it may as well be compressed!
# .widget-social {
#   text-align: right; }
#   .widget-social a,
#   .widget-social a:visited {
#     padding: 0 3px;
#     color: #222222;
#     color: rgba(34, 34, 34, 0.77); }
#   .widget-social a:hover {
#     color: #B00909; }
#
# :expanded
# .widget-social {
#   text-align: right;
# }
# .widget-social a,
# .widget-social a:visited {
#   padding: 0 3px;
#   color: #222222;
#   color: rgba(34, 34, 34, 0.77);
# }
# .widget-social a:hover {
#   color: #B00909;
# }
#
# :compact
# .widget-social { text-align: right; }
# .widget-social a, .widget-social a:visited { padding: 0 3px; color: #222222; color: rgba(34, 34, 34, 0.77); }
# .widget-social a:hover { color: #B00909; }
#
# :compressed
# .widget-social{text-align:right}.widget-social a,.widget-social a:visited{padding:0 3px;color:#222222;color:rgba(34,34,34,0.77)}.widget-social a:hover{color:#B00909}
#
# Don't chase your tail too long on this ...
# If you change the sass style, stop the serve and rebuild it.
sass: { style: compressed }
# style: compressed
