


# _config-prod.yml:

# Overrides for _config.yml when pushing site to production, e.g. via ftp.
# - e.g. perhaps changing the base url to /Jekyll, or something.
# Confirmed: github runs with 'JEKYLL_ENV=production', baseurl: "/dev".

# NOTE: IF YOU SET A VALUE ... YOU *MUST* SET *ALL* VALUES!
# - each subsequent setting overrides ALL of a prior setting.
# e.g. myvar: { a true, b false } in _config-base.yml
#      myvar: {a false } here
#      LEAVES myvar.b UNSET!


#baseurl: ""
#baseurl: /dev # /dev now default.

url: "http://localhost:4000"
#    - successfully sets ... AND .. is still getting jekyll served at :4000!
#    - remember to chmod o+r * after generation, or apache2 won't be able to
#      read (or serve) the files.

#url: "http://www.kwootc.ca"


jekyll_tidy: { compress_html: true, exclude: [ "this doesn't work" ] }

# sass defaults to compressed, per _config-base.yml.
# Nevermind that settings beyond _config-base.yml seem to have no effect.
