theme: jekyll-theme-slate
name: www.kwootc.ca Development Website
title: [www.kwootc.ca Development]
description: [www.kwootc.ca Development Repository]
show_downloads: "false"
my_google_analytics: [Your Google Analytics tracking ID - Remove the my_ when you figure this out]
markdown: kramdown

# https://help.github.com/articles/basic-writing-and-formatting-syntax/

permalink: /diary/:year/:month/:day/:title

gems:
  - jekyll-sitemap
  - jekyll-paginate
